
# This yaml involves configurations to create an AWS stack of resources using cloudformation

Parameters:
  parameterIPForSSHAccess:
    Description: Enter the IP address(or range) of the ssh clients which can access the EC2 instance. This is to add a layer of security by limiting SSH access to a specific number of clients. Failing to configure this parameter, a client with any IP address can gain SSH access to the EC2 instance if he has the required key pair
    Type: String
    Default: 0.0.0.0/0

  parameterIPForServerAccess:
    Description: Enter the IP address(or range) of the HTTP clients which can hit the Django webserver. This is to add a layer of security by limiting HTTP access to a specific number of clients. Failing to configure this parameter, a client with any IP address can access the server
    Type: String
    Default: 0.0.0.0/0
    
  parameterUserData:
    Description: script which will act as a userdata to initialize the EC2 instance during boot time 
    Type: String
    
  parameterSSHKeyPair:
    Description: Enter the key-pair name which shall be used for SSH access 
    Type: String
    Default: my-key-pair

# create an EC2 instance 
Resources:
  resourceEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-0b44050b2d893d5f7
      InstanceType: t2.micro
      KeyName: !Ref parameterSSHKeyPair
      UserData: !Ref parameterUserData
      SecurityGroups:
        - !Ref resourceSecurityGroupForSSH
        - !Ref resourceSecurityGroupForDjangoServer
      Tags: 
        - Key: Name
          Value: Django-EC2Instance


# security group to enable ssh access 
  resourceSecurityGroupForSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
     GroupDescription: Configure SSH access to the EC2 instance
     SecurityGroupIngress:
     - CidrIp: !Ref parameterIPForSSHAccess
       IpProtocol: tcp
       FromPort: 22
       ToPort: 22


# security group to access the Django webserver 
  resourceSecurityGroupForDjangoServer:
    Type: AWS::EC2::SecurityGroup
    Properties:
     GroupDescription: Configure access to the Django webserver
     SecurityGroupIngress:
     - CidrIp: !Ref parameterIPForServerAccess
       IpProtocol: tcp
       FromPort: 8080
       ToPort: 8080

